
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Max: 198
Metrics/PerceivedComplexity:
  Max: 9
Metrics/MethodLength:
  Max: 12
Metrics/BlockLength:
  Max: 47
Metrics/CyclomaticComplexity:
  Max: 9